project_id = "oufatfjbdjezsfvvjhcp"

[functions.chat-buddy]
verify_jwt = false

[functions.talk-buddy-chat]
verify_jwt = false

[functions.listen-buddy-generate]
verify_jwt = false

[functions.listen-buddy-respond]
verify_jwt = false

[functions.read-buddy-generate]
verify_jwt = false
